version: "3.8"

services:
  app:
    init: true
    image: gradle:8.8.0-jdk17
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    command: sh -cx 'gradle assemble && exec java -jar build/libs/demo-0.0.1-SNAPSHOT.jar'
#    command: ["/bin/sh", "-c", "while true; do sleep 86400; done;"]
    environment:
      - GRADLE_OPTS=-Xmx512m -Dorg.gradle.daemon=false
      - JAVA_TOOL_OPTIONS=-XX:MaxRAM=512m -XX:+StartAttachListener
      - SPRING_DATA_REDIS_PORT=6222
    ports:
      - 7080:7080
      - 7081:7081
    depends_on:
      - test-redis

  test-redis:
    image: redis:7.2.1-alpine
    ports:
      - 6222:6379
    hostname: asp-redis
    command: redis-server --port 6379 --enable-debug-command local
