server:
  port: 7080
spring:
  data:
    redis: # Redis Properties
      host: localhost
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
      password:
      port: ${SPRING_DATA_REDIS_PORT:6222}
      ssl:
        enabled: false
      timeout: 3s
logging:
  level:
    root: info

# disable metrics export resolves the issue
#management:
#  defaults:
#    metrics:
#      export:
#        enabled: false

management:
  server:
    port: 7081
  endpoint:
    threaddump:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,threaddump

